CREATE OR REPLACE FUNCTION STUD11.CREDIT_RAT(V_NAME IN VARCHAR2)
  RETURN VARCHAR2
  AS
    V_TEST NUMBER;
    V_RES VARCHAR2(20);
  BEGIN
    SELECT COUNT(*)
    INTO V_TEST
    FROM S_CUSTOMER 
    WHERE NAME = V_NAME;

    IF(V_TEST != 0) THEN
      SELECT CREDIT_RATING
      INTO V_RES
      FROM S_CUSTOMER
      WHERE NAME = V_NAME;
    ELSE
      V_RES := '0';
    END IF;

    RETURN V_RES;

  END;