CREATE OR REPLACE FUNCTION STUD11.SALARY (V_LAST IN VARCHAR2)
  RETURN NUMBER
  AS
    V_TEST NUMBER;
    V_RES NUMBER;
  BEGIN
    SELECT COUNT(LAST_NAME)
    INTO V_TEST
    FROM S_EMP
    WHERE LAST_NAME = V_LAST;
    
    IF(V_TEST != 0) THEN
      SELECT MAX(SALARY)
      INTO V_RES
      FROM S_EMP
      WHERE LAST_NAME = V_LAST;

    ELSE
      V_RES := 0;
    END IF;

    RETURN V_RES;
  END;
/